### ISSUE TITLE
Does this available in a maven repository somewhere?

### ISSUE THREAD

**Issue by ctran** [Zetten/xvfb-maven-plugin#1]

**Comment by Zetten** [comment]
I'm afraid not - since so far I'm the only one using it (as far as I know), I'd ideally like to get a few more reports of success/failure before trying to submit it anywhere. Feel free to play around with it and let me know :smiley:

In particular the `setDisplayEnvVar` property needs a bit more testing in different environments. Setting the `$DISPLAY` environment variable from within the running JVM is a bit of a hack, and I haven't used it in any serious way. If you can use the exported Maven property it's probably safer.

**Comment by ctran** [comment]
Thanks for the quick answer.

**Comment by Toilal** [comment]
:+1:

Probably nobody will never use it if it's not on maven central :(

I gave it a try on my development computer, and it just works ! good work, but please launch this in the wild !

At the moment sadly, it's a no go because if it's not available on maven central.

**Comment by Zetten** [comment]
I've started the process of getting it in Central now.

I was a bit hestitant to just push it out into the wild without more testing, but it's being used in a few places now and I haven't heard any real complaints, so thanks for your votes of confidence.

**Comment by Zetten** [comment]
It's now available in Central (via Sonatype's OSSRH so any snapshots/staging will be there).

```
<plugin>
    <groupId>com.github.zetten</groupId>
    <artifactId>xvfb-maven-plugin</artifactId>
    <version>1.0.2</version>
</plugin>
```

**Comment by Toilal** [comment]
Many many thanks ! It works :)
